name: Build and Push to ECR

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: Global

    - name: Login to ECR registry
      run: aws ecr get-login-password --region Global | docker login --username AWS --password-stdin public.ecr.aws/k6n2s2b9/sample

    - name: Build and push Docker image
      run: |
        docker build -t public.ecr.aws/k6n2s2b9/sample:latest .
        docker push public.ecr.aws/k6n2s2b9/sample:latest
