name: Docker Build

on:
  push:
    branches:
      - main  # Replace with your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-image-name:tag .
          docker tag your-image-name:tag your-dockerhub-username/your-image-name:tag
          docker push your-dockerhub-username/your-image-name:tag
