name: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build with Maven
        run: mvn clean package

      - name: Store build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-artifacts
          path: target/quarkus-app    # Adjust this path to match your Maven output

  # Add other jobs for testing, etc., if needed
